baseURL: "https://chloe-baubier.netlify.app/"
languageCode: en-us
title: Website of Chloé Baubier
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A WEBSITE CREATED BY CHLOE BAUBIER
    #  AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Movie analytics
  blog: {}
  contact:
   address:
      - city: London, NW1 4SA
  #      country: Country
        street: Regent's Park
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: cbaubier@gmail.com
        title: Email
    enable: yes
    phone:
     - phone: +44 (0)20 7000 7000
        title: Phone
  #custom_css: []
  #custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Movie Analytics
    enable: yes
   # quicklinks:
   #   - alt: HTML5 UP
     #   text: 'Design: '
     #   url: https://www.html5up.net
    social:
     # - icon: fa-twitter
     #   label: Twitter
     #   url: https://www.twitter.com
  #    - icon: fa-facebook
  #      label: Facebook
    #    url: https://www.facebook.com
  #    - icon: fa-instagram
   #     label: Instagram
    #    url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/cbaubier
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/chloe-baubier-77340/
  image: ''
  name: Chloé Baubier
  navigation:
  #  button1:
  #    - name: Explore
   #     url: blogs
   # button2:
   #   - name: Log In
   #     url: '#'
    links:
      - name: Home
        url: '#'
      - name: Now showing
        url: blogs
     # - name: Upcoming releases
     #   url: projects/project4
    #  - name: Elements
    #    url: elements.html
    menu: Menu
 #   subtitle: By HTML5 Up
    title: Home
  tiles:
    enable: yes
    showcase:
      - image: projects/image1.jpg
      #  subtitle: 
        title: About me
        url: projects/project0
      - image: projects/image2.jpg
       # subtitle: Feugiat Amet Tempus
        title: Statistics of the industry
        url: projects/project1
      - image: projects/image3.jpg
       # subtitle: Lorem Etiam Nullam
        title: Burton vs Spielberg
        url: projects/project2
      - image: projects/image4.jpg
       # subtitle: Nisl Sed Aliquam
        title: Save private ~~Ryan~~ cinema
        url: projects/project3
     # - image: pic05.jpg
     #   subtitle: Ipsum Dolor Sit Amet
     #  title: Consequat
      #  url: blogs/ipsum
     # - image: pic06.jpg
     #   subtitle: Feugiat Amet Tempus
     #   title: Etiam
     #   url: blogs/ipsum
  two:
    buttonText: Check it out
    enable: yes
  # subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
  #    \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
   #   condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
   #   pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
    #  Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
    #  amet pharetra et feugiat tempus."
    title: See what movies are currently showing
    url: blogs
